global:
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false

  file:
    directory: "/etc/traefik/config"
    watch: true

log:
  level: INFO
  format: common

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: email@email.com
      storage: acme.json
      keyType: EC384
      httpChallenge:
        entryPoint: http

  letsencrypt-legacy:
    acme:
      email: email@email.com
      storage: acme.json
      keyType: EC384
      preferredChain: 'DST Root CA X3'
      httpChallenge:
        entryPoint: http
# Allow insecure backend certificates 
serversTransport:
  insecureSkipVerify: true
